// Auto-generated by LibreLane
module hsrmteam1(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
  inout IOVSS,
  inout IOVDD,
`endif
  inout clk_PAD,
  inout rst_n_PAD,
  inout[2:0] input_PAD,
  inout[12:0] output_PAD
);
endmodule
